#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "automatic-ripping-machine"
name = "Automatic Ripping Machine"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "2.23.1~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "MIT"
website = "https://b3n.org/automatic-ripping-machine"
admindoc = "https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki"
code = "https://github.com/automatic-ripping-machine/automatic-ripping-machine"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "amd64"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[antifeatures]
non-free-dependencies.en = "To rip DVDs or Blurays, it makes use of MakeDVD which is partially open-source but proprietary software and for which you may have to purchase a license at some point."
non-free-dependencies.fr = "Pour ripper des DVD ou des Bluray, MakeDVD est utilisé. Or il s'agit d'un logiciel en partie open-source mais propriétaire pour lequel vous pourriez devoir à terme acheter une licence."

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/automatic-ripping-machine/automatic-ripping-machine/archive/refs/tags/2.23.1.tar.gz"
    sha256 = "4789920b892b85e7acf9febe36c3355191b264fd474a7df65ebd54e07851b7db"
    rename = "automatic-ripping-machine.tar.gz"
    autoupdate.strategy = "latest_github_tag"
    
    [resources.sources.makemkv_bin]
    url = "https://www.makemkv.com/download/makemkv-bin-1.18.3.tar.gz"
    sha256 = "c1ee720ae91b276a7c89be861146c5b934631831e8d6c8f453406435724e92bd"
    rename = "makemkv-bin.tar.gz"
    
    [resources.sources.makemkv_oss]
    url = "https://www.makemkv.com/download/makemkv-oss-1.18.3.tar.gz"
    sha256 = "bc8bb084ae3aabcd503d5bb93efc273e046e4fd4663d39a9836ce0c047fee823"
	rename = "makemkv-oss.tar.gz"
    
    [resources.sources.handbrake]
    url = "https://github.com/HandBrake/HandBrake/releases/download/1.11.1/HandBrake-1.11.1-source.tar.bz2"
    sha256 = "4ff6a8a57c9b1cea51025306e313eee423b0fa1a8b7799aeaa8d4d7c457a7310"
    rename = "handbrake.tar.gz"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "HandBrake-.*-source.tar.bz2"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["db", "logs/progress", "media/transcode", "media/completed", "media/raw", "music"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ["autoconf", "automake", "build-essential", "cmake", "git", "libass-dev", "libbz2-dev", "libdrm-dev", "libfontconfig-dev", "libfreetype6-dev", "libfribidi-dev", "libharfbuzz-dev", "libjansson-dev", "liblzma-dev", "libmp3lame-dev", "libnuma-dev", "libogg-dev", "libopus-dev", "libsamplerate0-dev", "libspeex-dev", "libtheora-dev", "libtool", "libtool-bin", "libturbojpeg0-dev", "libva-dev", "libvorbis-dev", "libx264-dev", "libxml2-dev", "libvpx-dev", "m4", "make", "meson", "nasm", "ninja-build", "patch", "pkg-config", "python3", "tar", "zlib1g-dev", "abcde", "at", "cdparanoia", "default-jre-headless", "eject", "ffmpeg", "flac", "glyrc", "imagemagick", "libcurl4-openssl-dev", "libdvdcss2", "libssl-dev", "lsdvd", "python3-venv", "python3-libdiscid", "python3-pip", "libdvd-pkg", "libavcodec-dev"]
