#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

# Backup dependencies binaries
mkdir -p "$install_dir/makemkv/bin"
cp /usr/bin/makemkvcon "$install_dir/makemkv/bin/makemkvcon"
cp /usr/bin/mmdtsdec "$install_dir/makemkv/bin/mmdtsdec"
cp /usr/share/MakeMKV "$install_dir/makemkv/bin/MakeMKV"

mkdir -p "$install_dir/makemkv/oss"
cp /usr/bin/mmgplsrv "$install_dir/makemkv/oss/mmgplsrv"
cp /usr/bin/mmccextr "$install_dir/makemkv/oss/mmccextr"
cp /usr/lib/libmmbd.so.0 "$install_dir/makemkv/oss/libmmbd.so.0"
cp /usr/lib/libdriveio.so.0 "$install_dir/makemkv/oss/libdriveio.so.0"
cp /usr/lib/libmakemkv.so.1 "$install_dir/makemkv/oss/libdriveio.so.1"

mkdir -p "$install_dir/handbrake"
cp /usr/local/bin/HandBrakeCLI "$install_dir/handbrake/HandBrakeCLI"

ynh_backup "$install_dir"

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup "$data_dir"

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

# Backup the NGINX configuration
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

# Backup the systemd service unit
ynh_backup "/etc/systemd/system/$app.service"

# Backup the logrotate configuration
ynh_backup "/etc/logrotate.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
