#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

makemkv_version=$(_read_manifest_resource_version "makemkv_bin")
ynh_app_setting_set --key=makemkv_version --value="$makemkv_version"

handbrake_version=$(_read_manifest_resource_version "handbrake")
ynh_app_setting_set --key=handbrake_version --value="$handbrake_version"

fetch_video_metadata_externally="false"
ynh_app_setting_set --key=fetch_video_metadata_externally --value="$fetch_video_metadata_externally"

skip_video_transcoding="false"
ynh_app_setting_set --key=skip_video_transcoding --value="$skip_video_transcoding"

min_video_length=600
ynh_app_setting_set --key=min_video_length --value="$min_video_length"

max_video_length=99999
ynh_app_setting_set --key=max_video_length --value="$max_video_length"

date_format="%m-%d-%Y %H:%M:%S"
ynh_app_setting_set --key=date_format --value="$date_format"

allow_duplicate_rips="false"
ynh_app_setting_set --key=allow_duplicate_rips --value="$allow_duplicate_rips"

auto_eject="true"
ynh_app_setting_set --key=auto_eject --value="$auto_eject"

handbrake_preset_dvd="HQ 720p30 Surround"
ynh_app_setting_set --key=handbrake_preset_dvd --value="$handbrake_preset_dvd"

handbrake_preset_bd="HQ 1080p30 Surround"
ynh_app_setting_set --key=handbrake_preset_bd --value="$handbrake_preset_bd"

omdb_api_key=""
ynh_app_setting_set --key=omdb_api_key --value="$omdb_api_key"

tmdb_api_key=""
ynh_app_setting_set --key=tmdb_api_key --value="$tmdb_api_key"

audio_cd_output_format="flac"
ynh_app_setting_set --key=audio_cd_output_format --value="$audio_cd_output_format"

audio_cd_trackname_format='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM} - ${TRACKFILE}'
ynh_app_setting_set --key=audio_cd_trackname_format --value="$audio_cd_trackname_format"

audio_cd_trackname_format_va='Various ${ALBUMFILE}/${TRACKNUM} ${ARTISTFILE} ${TRACKFILE}'
ynh_app_setting_set --key=audio_cd_trackname_format_va --value="$audio_cd_trackname_format_va"

notifications_config_path=""
ynh_app_setting_set --key=notifications_config_path --value="$notifications_config_path"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Install libdvdcss, used by libdvd-pkg which was installed via apt
dpkg-reconfigure --frontend=noninteractive libdvd-pkg

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

# Add dependencies' `requirements.txt` file to `arm-dependencies` folder
ynh_setup_source --dest_dir="$install_dir/arm-dependencies" --source_id="arm_dependencies"
find "$install_dir/arm-dependencies" -mindepth 1 -type d -exec rm --recursive --force {} + #remove everything in the folder but requirements.txt
ls -la $install_dir/arm-dependencies
ls -la $install_dir
find "$install_dir/arm-dependencies" -mindepth 1 ! -name "requirements.txt" -exec rm --recursive --force {} + #remove everything in the folder but requirements.txt

#=================================================
# BUILD MAKEMKV
#=================================================
ynh_script_progression "Building MakeMKV (this can take some time)..."

_build_makemkv

#=================================================
# BUILD HANDBRAKE CLI
#=================================================
ynh_script_progression "Building Handbrake CLI (this will take even more time)..."

_build_handbrake

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

mkdir -p "$install_dir/app_config"
ynh_config_add --template=".env" --destination="$install_dir/app_config/.env"
ynh_config_add --template="arm.yaml" --destination="$install_dir/app_config/arm.yaml"
ynh_config_add --template="apprise.yaml" --destination="$install_dir/app_config/apprise.yaml"
ynh_config_add --template=".abcde.conf" --destination="$install_dir/app_config/.abcde.conf"

chown -R "$app:$app" "$install_dir"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================

pushd $install_dir
	ynh_exec_as_app python3 -m venv $install_dir/venv
	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/pip install --upgrade pip wheel
	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/pip install -r requirements.txt
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Automatic ripping machine UI" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

# Create udev rule
ynh_config_add --template="udev.rules" --destination="$install_dir/app_config/51-automatic-ripping-machine-venv.rules"
ln -sf "$install_dir/app_config/51-automatic-ripping-machine-venv.rules" /lib/udev/rules.d

# Configure automount for the optical drive
for dev in /dev/sr?; do
    grep -q "${dev}    /mnt${dev}    udf,iso9660    defaults,users,utf8,ro    0    0" /etc/fstab
    if [ $? -ne 0 ]; then
        echo -e "${dev}    /mnt${dev}    udf,iso9660    defaults,users,utf8,ro    0    0 " | tee -a /etc/fstab
    fi
    mkdir -p "/mnt$dev"
done

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
