#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Unmount drives and remove app-related fstab entries
for dev in /dev/sr?; do
    umount -f "/mnt$dev"
    sed -i "/${dev}    /mnt${dev}    udf,iso9660    defaults,users,utf8,ro    0    0/d" /etc/fstab
done

# Remove udev rule
unlink /lib/udev/rules.d/51-automatic-ripping-machine-venv.rules

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
