#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Unmount drives and remove app-related fstab entries
for dev in /dev/sr?; do
    umount -f "/mnt$dev"
    rmdir "/mnt$dev"
    sed -i "\@${dev}    /mnt${dev}    udf,iso9660    defaults,users,utf8,ro    0    0@d" /etc/fstab
done
ynh_replace --match="#disabled_by_yunohost_automatic_ripping_machine_package_install#" --replace="" --file="/etc/fstab"

# Remove udev rule
unlink /lib/udev/rules.d/51-automatic-ripping-machine-venv.rules

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

ynh_config_remove_nginx

#=================================================
# REMOVE APP SYSTEM FILES
#=================================================
ynh_script_progression "Removing system files related to $app..."

# MakeMKV bin
unlink /usr/bin/sdftool
ynh_safe_rm /usr/bin/makemkvcon
ynh_safe_rm /usr/bin/mmdtsdec
ynh_safe_rm /usr/share/MakeMKV

# MakeMKV oss
ynh_safe_rm /usr/bin/mmgplsrv
ynh_safe_rm /usr/bin/mmccextr
ynh_safe_rm /usr/lib/libmmbd.so.0
ynh_safe_rm /usr/lib/libmakemkv.so.1
ynh_safe_rm /usr/lib/libdriveio.so.0
ldconfig

# Handbrake
ynh_safe_rm /usr/local/bin/HandBrakeCLI

# remove libdvdcss2 (this package was installed via the install script, not by core)
if [ $was_libdvdcss2_originally_installed == "false" ]; then
    ynh_hide_warnings apt --yes remove libdvdcss2
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
