#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================

ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

# Create udev rule
ln -sf "$install_dir/app_config/51-automatic-ripping-machine-venv.rules" /lib/udev/rules.d

# Configure automount for the optical drive
for dev in /dev/sr?; do
    grep -q "${dev}    /mnt${dev}    udf,iso9660    defaults,users,utf8,ro    0    0" /etc/fstab
    if [ $? -ne 0 ]; then
        echo -e "${dev}    /mnt${dev}    udf,iso9660    defaults,users,utf8,ro    0    0 " | tee -a /etc/fstab
    fi
    mkdir -p "/mnt$dev"
done

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
