#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="app_config"

#=================================================
# BUILD MAKEMKV
#=================================================
makemkv_version_previous=$(ynh_app_setting_get --key=makemkv_version)
makemkv_version=$(_read_manifest_resource_version "makemkv_bin")

if $(dpkg --compare-versions "$makemkv_version_previous" "ne" "$makemkv_version"); then 
    ynh_script_progression "Building MakeMKV (this can take some time)..."
  
    _build_makemkv
    ynh_app_setting_set --key=makemkv_version --value=$makemkv_version
fi

#=================================================
# BUILD HANDBRAKE CLI
#=================================================
handbrake_version_previous=$(ynh_app_setting_get --key=handbrake_version)
handbrake_version=$(_read_manifest_resource_version "handbrake")

if $(dpkg --compare-versions "$handbrake_version_previous" "ne" "$handbrake_version"); then 
    ynh_script_progression "Building Handbrake CLI (this can take some time)..."
  
    _build_handbrake
    ynh_app_setting_set --key=handbrake_version --value=$handbrake_version
fi

#=================================================
# UPDATE PYTHON DEPENDENCIES
#=================================================

pushd $install_dir
	ynh_exec_as_app python3 -m venv $install_dir/venv
	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/pip install --upgrade pip wheel
	ynh_hide_warnings ynh_exec_as_app $install_dir/venv/bin/pip install -r requirements.txt
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Automatic ripping machine UI" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
